import pandas as pd
import re
import streamlit as st
import plotly.express as px

class BusinessQueryEngine:
    @staticmethod
    def execute_query(df, question):
        """
        Parses natural language business query and executes it against the DataFrame.
        Returns a dictionary with result description, metric/dataframe, and optional chart.
        """
        q = question.lower().strip()
        
        # 1. Sales / Profit metrics
        if any(w in q for w in ["total sales", "gross revenue", "total revenue"]):
            total_sales = df['Sales'].sum()
            return {
                "type": "metric",
                "label": "Total Revenue",
                "value": f"${total_sales:,.2f}",
                "desc": "Accumulated gross revenue across all transactions."
            }
            
        if any(w in q for w in ["total profit", "net profit", "overall profit"]):
            total_profit = df['Profit'].sum()
            return {
                "type": "metric",
                "label": "Net Profit",
                "value": f"${total_profit:,.2f}",
                "desc": "Net profit after discounts across all transactions."
            }
            
        if "average discount" in q:
            avg_disc = df['Discount'].mean() * 100
            return {
                "type": "metric",
                "label": "Average Discount",
                "value": f"{avg_disc:.2f}%",
                "desc": "Mean discount rate applied across orders."
            }

        # 2. Top / Best performing categories or sub-categories
        match_top_cat = re.search(r"top\s+(\d+)\s+(category|categories|sub-category|sub-categories|sub_category|sub_categories)", q)
        if match_top_cat:
            limit = int(match_top_cat.group(1))
            col = 'Sub_Category' if 'sub' in match_top_cat.group(2) else 'Category'
            top_df = df.groupby(col)['Sales'].sum().reset_index().sort_values('Sales', ascending=False).head(limit)
            
            fig = px.bar(top_df, x='Sales', y=col, orientation='h', 
                         title=f"Top {limit} {col} by Sales",
                         template='plotly_dark', color='Sales', color_continuous_scale='Purp')
            fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
            
            return {
                "type": "table_chart",
                "desc": f"The top {limit} performing {col.replace('_', ' ')} segments ranked by absolute revenue.",
                "data": top_df,
                "chart": fig
            }

        # 3. Correlation between metrics
        if "correlation" in q or "relationship" in q:
            corr_df = df[['Sales', 'Profit', 'Discount', 'Quantity']].corr()
            fig = px.imshow(corr_df, text_auto=True, color_continuous_scale='RdBu_r', 
                            template='plotly_dark', title="Key Metrics Correlation Matrix")
            fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
            return {
                "type": "chart",
                "desc": "Correlation matrix analyzing relations between Sales, Profit, Discount and Quantity. Values closer to 1 or -1 show strong positive/negative linear relationships.",
                "chart": fig
            }

        # 4. Regional mix or breakdown
        if "region" in q or "regional" in q:
            reg_df = df.groupby('Region')['Sales'].sum().reset_index()
            fig = px.pie(reg_df, values='Sales', names='Region', hole=0.5,
                         title="Sales Distribution by Region", template='plotly_dark',
                         color_discrete_sequence=px.colors.sequential.Purp)
            fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
            return {
                "type": "table_chart",
                "desc": "Proportion of total gross revenue generated by each major region.",
                "data": reg_df,
                "chart": fig
            }

        # 5. Segment performance (Corporate / Consumer)
        if "segment" in q:
            seg_df = df.groupby('Segment')['Sales'].sum().reset_index()
            fig = px.bar(seg_df, x='Segment', y='Sales', title="Sales by Customer Segment",
                         template='plotly_dark', color='Sales', color_continuous_scale='Purp')
            fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
            return {
                "type": "table_chart",
                "desc": "Sales performance grouped by customer business segment.",
                "data": seg_df,
                "chart": fig
            }

        # Default fallback instructions
        return {
            "type": "fallback",
            "desc": "Unable to execute query. Let's try some standard queries:",
            "suggestions": [
                "What is the total sales?",
                "What is the total profit?",
                "Show top 5 sub-categories",
                "Show regional mix",
                "What is the correlation between profit and discount?",
                "Show average discount"
            ]
        }

def show_query_engine(df):
    st.title("Business Query Intelligence")
    st.markdown("Query the active dataset using a local natural language parser.")
    st.markdown("---")
    
    st.markdown('<div class="glass-card">', unsafe_allow_html=True)
    st.subheader("Data Analyst Query Bar")
    question = st.text_input(
        "Ask a business intelligence question (e.g. 'Show top 5 sub-categories' or 'What is the correlation?')",
        value="Show top 5 sub-categories",
        label_visibility="collapsed"
    )
    st.markdown('</div>', unsafe_allow_html=True)
    
    if question:
        with st.spinner("Analyzing dataset..."):
            res = BusinessQueryEngine.execute_query(df, question)
            
        st.markdown('<div class="glass-card glow-blue">', unsafe_allow_html=True)
        st.write(f"**Analysis Insight:** {res['desc']}")
        st.markdown('</div>', unsafe_allow_html=True)
        
        if res['type'] == 'metric':
            st.metric(res['label'], res['value'])
            
        elif res['type'] == 'chart':
            st.plotly_chart(res['chart'], use_container_width=True)
            
        elif res['type'] == 'table_chart':
            c1, c2 = st.columns([1, 2])
            with c1:
                st.dataframe(res['data'], use_container_width=True)
            with c2:
                st.plotly_chart(res['chart'], use_container_width=True)
                
        elif res['type'] == 'fallback':
            st.warning("Query not matched. Please select from one of our template queries:")
            for sugg in res['suggestions']:
                st.code(sugg)
